hw-3
nixiieee/hse-ml-course-2024-hw pull request #3
Opened 2024-02-23 22:32 UTC by nixiieee

2024-03-02 06:32 UTC, svkov requested changes
С medium все ок, easy надо доделать

Ну и второй ноутбук надо спасти)

2024-03-02 06:32 UTC, svkov commented on notebooks/02-homework.ipynb
зачем удаляешь ноутбук? если так смержить, то в итоговом репо не будет второго ноутбука.

сделай реверт и закоммить только 3 ноутбук

2024-03-02 06:32 UTC, svkov commented on notebooks/03-homework.ipynb
> +    "Обоснование выбора метрики: интуитивно понятная метрика, показывающая, какую долю объектов классификатор смог верно предсказать"
Правда ли, что accuracy честная метрика на этих данных? Может ли быть ситуация, что какой-то класс мы вообще не учли, а accuracy будет высоким?

2024-03-02 09:23 UTC, nixiieee commented
> С medium все ок, easy надо доделать
> 
> Ну и второй ноутбук надо спасти)

А что по поводу hard?

2024-03-02 10:23 UTC, nixiieee commented on notebooks/02-homework.ipynb
Его не получается удалить, потому что я случайно ответвилась от hw-2. Можно новую ветвь создать?

2024-03-04 06:38 UTC, svkov commented on notebooks/02-homework.ipynb
Сделай так, чтобы в итоге второй ноутбук не потерялся)

2024-03-04 06:41 UTC, svkov commented
> А что по поводу hard?

Не увидел)

Правда ли, что 5к картинок - достаточно?
Можно ли взять меньше? Если да, то на сколько?
5к картинок из каких классов надо взять? Есть ли классы, которым надо больше/меньше данных, чем остальным?

Ну и нужно написать код для ответа на эти вопросы

2024-03-09 11:41 UTC, svkov approved these changes
Супер! Первый зачтенный хард!

2024-03-15 19:22 UTC, merged